# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SQUIC_R <- function(Y1, lambda, max_iter, drop_tol, term_tol, verbose, mode, M, X0, W0, Y2) {
    .Call(`_SQUIC_SQUIC_R`, Y1, lambda, max_iter, drop_tol, term_tol, verbose, mode, M, X0, W0, Y2)
}

