# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SQUIC_BASE <- function(mode, data_train, lambda, max_iter, drop_tol, term_tol, M, X0, W0, data_test, verbose) {
    .Call(`_SQUIC_SQUIC_BASE`, mode, data_train, lambda, max_iter, drop_tol, term_tol, M, X0, W0, data_test, verbose)
}

